import { GreenTick } from '../components/GreenTick';
import { RedTick } from '../components/RedTick';

export const features = [
  {
    key: 1,
    title: '100+ Beginner Problems',
    subTitle: 'Perfect for starting out with zero knowledge.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 2,
    title: '300 Curated Problems',
    subTitle: 'Sorted by topic and difficulty for mastering DSA.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 3,
    title: 'Topic-Based Contests',
    subTitle: 'Test your knowledge after each topic.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 4,
    title: 'Mixed Topic Contests',
    subTitle: 'Comprehensive challenges at course end.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 5,
    title: 'Personalized Roadmap',
    subTitle: 'Daywise plan tailored to your entered timeline.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 6,
    title: 'Customizable Schedule',
    subTitle: 'Adapt your roadmap to your needs.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 7,
    title: 'Video Solutions',
    subTitle: 'Step-by-step individual videos for brute to optimal.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 8,
    title: 'Detailed Editorials',
    subTitle: 'High-quality image explanations for clarity.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 9,
    title: 'Guess the Output',
    subTitle: 'Enhance problem understanding.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 10,
    title: 'Practice Portal',
    subTitle: 'Access to all problems including premium ones outside.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 11,
    title: 'AI-Assisted Doubt Portal',
    subTitle: 'Get instant help with our trained model.',
    sprint: <RedTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 12,
    title: 'Code Review',
    subTitle: 'Improve your code to industry standards.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 13,
    title: 'Complexity Analysis',
    subTitle: 'Evaluate time and space efficiency.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 14,
    title: 'Real-Life Examples',
    subTitle: 'Practical applications for every problem',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 15,
    title: 'Rich Text Editor',
    subTitle: 'Save notes in your preferred style.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 16,
    title: 'Weekly Sessions',
    subTitle: 'Meet with Striver and other experts.',
    sprint: <RedTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 17,
    title: 'Progress Tracking',
    subTitle: 'Monitor your advancement.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 18,
    title: 'Leaderboard',
    subTitle: 'Compete with others or opt-out.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 19,
    title: 'Completion Certificate',
    subTitle: 'Showcase your achievement.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 20,
    title: 'Exclusive Community',
    subTitle: 'Access to TUF+ discussions and Discord.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 21,
    title: 'Affiliate Program',
    subTitle: 'Earn more than what you paid by sharing.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
  {
    key: 22,
    title: 'Multi-Language Support',
    subTitle: 'C++, Java, Python, JavaScript.',
    sprint: <GreenTick />,
    pinnacle: <GreenTick />,
  },
];
